name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-06"

 compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWUyNTMzNzgtMGFiYi00MjllLWIyMGQtYzJkOWFmMDNkNDhhIiwidGVuYW50X2lkIjoiYmQxZGU1ZTY2NTUwOWZkNjcxOGZmZDE4YWYxMzBmOTQyOTA1NzdmNmFkOTg1NDczNTE1YWUwNDQ1YzViZGE1NCIsImludGVybmFsX3NlY3JldCI6IjAyMGFmNDgzLWYwMDgtNGU0Zi1iMzJmLTAzY2ZlZjI0ZjNmMCJ9.DRQntD3rA8aFBlXfS7klsfeLOLndSGIIV2DrrQtLzss"

JWT_SECRET="sameersecret"